using Assignment.Entities;
using System;
using System.Collections.Generic;

namespace Assigment.Database
{

    public  class MyDatabase
    {

        public List<Address> addresses { get; protected set; } = new List<Address>();
        public List<Disease> diseases { get; protected set; } = new List<Disease>();
        public List<Doctor> doctors { get; protected set; } = new List<Doctor>();
        public List<Patient> patients { get; protected set; } = new List<Patient>();
        public List<Room> rooms { get; protected set; } = new List<Room>();

        private MyDatabase()
        {
            
            Address A1 = new Address() { Id = 1, Name = "831 Locust Dr.", Country = "US", City = "Bayonne", PostalCode = "NJ 07002" };
            Address A2 = new Address() { Id = 2, Name = "425 Ashley St.", Country = "US", City = "Hoboken", PostalCode = "NJ 07030" };
            Address A3 = new Address() { Id = 3, Name = "572 St Louis Street", Country = "US", City = "Bakersfield", PostalCode = "CA 93306" };
            Address A4 = new Address() { Id = 4, Name = "448 Franklin Ave.", Country = "US", City = "Watertown", PostalCode = "MA 02472" };
            Address A5 = new Address() { Id = 5, Name = "23 Park Drive", Country = "US", City = "Willingboro", PostalCode = "NJ 08046" };
            Address A6 = new Address() { Id = 6, Name = "8488 East Addison St.", Country = "US", City = "Gettysburg", PostalCode = "PA 17325" };
            Address A7 = new Address() { Id = 7, Name = "474 Honey Creek Lane", Country = "US", City = "Natick", PostalCode = "MA 01760" };
            Address A8 = new Address() { Id = 8, Name = "41 Longfellow Street", Country = "US", City = "Jeffersonville", PostalCode = "IN 47130" };
            Address A9 = new Address() { Id = 9, Name = "53 Lantern Drive", Country = "US", City = "Salt Lake City", PostalCode = "UT 84119" };
            Address A10 = new Address() { Id = 10, Name = "10 Pawnee Road", Country = "US", City = "Torrington", PostalCode = "CT 06790" };
            Address A11 = new Address() { Id = 11, Name = "39 Cedarwood Lane", Country = "US", City = "Greenville", PostalCode = "NC 27834" };
            Address A12 = new Address() { Id = 12, Name = "514 Grange Road", Country = "UK", City = "WARRINGTON", PostalCode = "WA16 6ST" };
            Address A13 = new Address() { Id = 13, Name = "80 Alexander Road", Country = "UK", City = "WEST LONDON", PostalCode = "W26 4GE" };
            Address A14 = new Address() { Id = 14, Name = "9691 South Street", Country = "UK", City = "SLOUGH", PostalCode = "SL31 0IA" };
            Address A15 = new Address() { Id = 15, Name = "97 New Road", Country = "UK", City = "PORTSMOUTH", PostalCode = "PO91 9PF" };
            Address A16 = new Address() { Id = 16, Name = "91 Church Lane", Country = "UK", City = "ABERDEEN", PostalCode = "AB20 4VX" };
            Address A17 = new Address() { Id = 17, Name = "52 Main Road", Country = "UK", City = "EAST LONDON", PostalCode = "E56 5TM" };
            Address A18 = new Address() { Id = 18, Name = "6 Richardson St.", Country = "TX", City = "Longview", PostalCode = "TX 75604" };
            Address A19 = new Address() { Id = 19, Name = "28 Acacia Street", Country = "TX", City = "San Antonio", PostalCode = "TX 78207" };
            Address A20 = new Address() { Id = 20, Name = "8099 Bald Hill St.", Country = "TX", City = "Dallas", PostalCode = "TX 75211" };
            Address A21 = new Address() { Id = 21, Name = "9097 West Mayfield St.", Country = "TX", City = "Houston", PostalCode = "TX 77023" };
            Address A22 = new Address() { Id = 22, Name = "97 NE. Elmwood Lane", Country = "TX", City = "Dallas", PostalCode = "TX 75230" };
            Address A23 = new Address() { Id = 23, Name = "29 Fordham Dr.", Country = "TX", City = "San Antonio", PostalCode = "TX 78250" };
            Address A24 = new Address() { Id = 24, Name = "8489 Newbridge Drive", Country = "CA", City = "Florenceville", PostalCode = "NB E7L 0A4" };
            Address A25 = new Address() { Id = 25, Name = "7118 Columbia Ave.", Country = "CA", City = "Coverdale", PostalCode = "NB E1J 6G3" };
            Address A26 = new Address() { Id = 26, Name = "720 Alderwood Street", Country = "CA", City = "Petite-Bourgogne", PostalCode = "QC H3J 0M6" };
            Address A27 = new Address() { Id = 27, Name = "52 Saxton Rd.", Country = "CA", City = "Elliot Lake", PostalCode = "ON P5A 0H1" };
            Address A28 = new Address() { Id = 28, Name = "507 N. Rose Dr.", Country = "CA", City = "Flin Flon", PostalCode = "MB R8A 7T4" };
            Address A29 = new Address() { Id = 29, Name = "87 Leatherwood St.", Country = "CA", City = "Edmundston", PostalCode = "NB E3V 7A7" };
            Address A30 = new Address() { Id = 30, Name = "318 Bowman Ave.", Country = "CA", City = "Mont-Joli", PostalCode = "QC G5H 4V2" };


            Disease D1 = new Disease() { Id = 1, Title = "Influenza", Duration = 32 };
            Disease D2 = new Disease() { Id = 2, Title = "Smallpox", Duration = 423 };
            Disease D3 = new Disease() { Id = 3, Title = "Chickenpox", Duration = 234 };
            Disease D4 = new Disease() { Id = 4, Title = "Mumps", Duration = 654 };
            Disease D5 = new Disease() { Id = 5, Title = "Measles", Duration = 34 };
            Disease D6 = new Disease() { Id = 6, Title = "Poliomyelitis ", Duration = 545 };
            Disease D7 = new Disease() { Id = 7, Title = "AIDS", Duration = 234 };
            Disease D8 = new Disease() { Id = 8, Title = "Zika disease", Duration = 276 };
            Disease D9 = new Disease() { Id = 9, Title = "Diphtheria", Duration = 324 };
            Disease D10 = new Disease() { Id = 10, Title = "Tuberculosis ", Duration = 245 };
            Disease D11 = new Disease() { Id = 11, Title = "Gonorrhoea", Duration = 644 };
            Disease D12 = new Disease() { Id = 12, Title = "Syphilis", Duration = 666 };
            Disease D13 = new Disease() { Id = 13, Title = "Tetanus", Duration = 6969 };
            Disease D14 = new Disease() { Id = 14, Title = "Cholera", Duration = 69420 };
            Disease D15 = new Disease() { Id = 15, Title = "Typhoid fever", Duration = 777 };
            Disease D16 = new Disease() { Id = 16, Title = "Ascariasis", Duration = 1313 };
            Disease D17 = new Disease() { Id = 17, Title = "Filariasis", Duration = 4343 };
            Disease D18 = new Disease() { Id = 18, Title = "Ringworm ", Duration = 1344 };
            Disease D19 = new Disease() { Id = 19, Title = "Cryptosporidiosis", Duration = 5435 };
            Disease D20 = new Disease() { Id = 20, Title = "Creutzfeldt-Jacob Disease", Duration = 4334 };
            Disease D21 = new Disease() { Id = 21, Title = "Malaria ", Duration = 8678 };
            Disease D22 = new Disease() { Id = 22, Title = "Q-Fever", Duration = 6678 };
            Disease D23 = new Disease() { Id = 23, Title = "Yersenia ", Duration = 4678 };
            Disease D24 = new Disease() { Id = 24, Title = "Vibriosis", Duration = 7890 };
            Disease D25 = new Disease() { Id = 25, Title = "Listeriosis ", Duration = 3245 };
            Disease D26 = new Disease() { Id = 26, Title = "Glanders", Duration = 65464 };
            Disease D27 = new Disease() { Id = 27, Title = "Diphtheria ", Duration = 7676 };
            Disease D28 = new Disease() { Id = 28, Title = "Brucellosis ", Duration = 4564 };
            Disease D29 = new Disease() { Id = 29, Title = "Anthrax ", Duration = 6466 };
            Disease D30 = new Disease() { Id = 30, Title = "Clostridium Perfringens", Duration = 6544 };


            Doctor DO1 = new Doctor() { Id = 1, FirstΝame = "Allie", LastΝame = "Holt", Age = 32, Salary = 50000, Address = A1 };
            Doctor DO2 = new Doctor() { Id = 2, FirstΝame = "Arturo", LastΝame = "Dean", Age = 45, Salary = 321564, Address = A2 };
            Doctor DO3 = new Doctor() { Id = 3, FirstΝame = "Killian", LastΝame = "Mcdaniel", Age = 54, Salary = 564654, Address = A3 };
            Doctor DO4 = new Doctor() { Id = 4, FirstΝame = "Leo", LastΝame = "Mcdonald", Age = 34, Salary = 5145588, Address = A4 };
            Doctor DO5 = new Doctor() { Id = 5, FirstΝame = "Annie", LastΝame = "Frederick", Age = 57, Salary = 3689884, Address = A5 };
            Doctor DO6 = new Doctor() { Id = 6, FirstΝame = "Angela", LastΝame = "Neal", Age = 23, Salary = 79875466, Address = A6 };
            Doctor DO7 = new Doctor() { Id = 7, FirstΝame = "Trevin", LastΝame = "Hatfield", Age = 42, Salary = 696969420, Address = A7 };
            Doctor DO8 = new Doctor() { Id = 8, FirstΝame = "Aedan", LastΝame = "Kirby", Age = 59, Salary = 333666999, Address = A8 };
            Doctor DO9 = new Doctor() { Id = 9, FirstΝame = "Adyson", LastΝame = "Zimmerman", Age = 19, Salary = 87895415, Address = A9 };
            Doctor DO10 = new Doctor() { Id = 10, FirstΝame = "Avah", LastΝame = "Mcmillan", Age = 22, Salary = 5456787, Address = A10 };
            Doctor DO11 = new Doctor() { Id = 11, FirstΝame = "Alondra", LastΝame = "Mosley", Age = 20, Salary = 420420420, Address = A11 };
            Doctor DO12 = new Doctor() { Id = 12, FirstΝame = "Jasper", LastΝame = "Collins", Age = 44, Salary = 8979854, Address = A12 };
            Doctor DO13 = new Doctor() { Id = 13, FirstΝame = "Finnegan", LastΝame = "Smith", Age = 55, Salary = 534657654, Address = A13 };
            Doctor DO14 = new Doctor() { Id = 14, FirstΝame = "Evelin", LastΝame = "Boyd", Age = 66, Salary = 15646841, Address = A14 };
            Doctor DO15 = new Doctor() { Id = 15, FirstΝame = "Lilian", LastΝame = "Kelly", Age = 22, Salary = 89789654, Address = A15 };
            Doctor DO16 = new Doctor() { Id = 16, FirstΝame = "Micaela", LastΝame = "Welch", Age = 33, Salary = 65486798, Address = A1 };
            Doctor DO17 = new Doctor() { Id = 17, FirstΝame = "Elsie", LastΝame = "Dyer", Age = 39, Salary = 56546454, Address = A2 };
            Doctor DO18 = new Doctor() { Id = 18, FirstΝame = "Gwendolyn ", LastΝame = "Farrell", Age = 23, Salary = 8657897564, Address = A3 };
            Doctor DO19 = new Doctor() { Id = 19, FirstΝame = "Norah", LastΝame = "Bentley", Age = 73, Salary = 548723454, Address = A4 };
            Doctor DO20 = new Doctor() { Id = 20, FirstΝame = "Mckinley", LastΝame = "Roy", Age = 40, Salary = 5486732456, Address = A5 };
            Doctor DO21 = new Doctor() { Id = 21, FirstΝame = "Francis", LastΝame = "Williamson", Age = 71, Salary = 2456751218, Address = A6 };
            Doctor DO22 = new Doctor() { Id = 22, FirstΝame = "Priscilla", LastΝame = "Hebert", Age = 53, Salary = 897985421, Address = A7 };
            Doctor DO23 = new Doctor() { Id = 23, FirstΝame = "Siena", LastΝame = "Mullins", Age = 45, Salary = 23148787, Address = A8 };
            Doctor DO24 = new Doctor() { Id = 24, FirstΝame = "Grace", LastΝame = "Randall", Age = 65, Salary = 8789566589, Address = A9 };
            Doctor DO25 = new Doctor() { Id = 25, FirstΝame = "Salvatore", LastΝame = "Andrade", Age = 33, Salary = 5486798, Address = A10 };
            Doctor DO26 = new Doctor() { Id = 26, FirstΝame = "Mercedes", LastΝame = "Keith", Age = 54, Salary = 418678897, Address = A11 };
            Doctor DO27 = new Doctor() { Id = 27, FirstΝame = "Kaya", LastΝame = "Castaneda", Age = 24, Salary = 15564654, Address = A12 };
            Doctor DO28 = new Doctor() { Id = 28, FirstΝame = "Lila", LastΝame = "Woodard", Age = 29, Salary = 685347, Address = A13 };
            Doctor DO29 = new Doctor() { Id = 29, FirstΝame = "Mauricio", LastΝame = "Hays", Age = 39, Salary = 876315, Address = A14 };
            Doctor DO30 = new Doctor() { Id = 30, FirstΝame = "Brooks", LastΝame = "Stevens", Age = 42, Salary = 46535351, Address = A15 };


            Room R1 = new Room() { Id = 1, Title = "ROOM 1" };
            Room R2 = new Room() { Id = 2, Title = "ROOM 2" };
            Room R3 = new Room() { Id = 3, Title = "ROOM 3" };
            Room R4 = new Room() { Id = 4, Title = "ROOM 4" };
            Room R5 = new Room() { Id = 5, Title = "ROOM 5" };
            Room R6 = new Room() { Id = 6, Title = "ROOM 6" };
            Room R7 = new Room() { Id = 7, Title = "ROOM 7" };
            Room R8 = new Room() { Id = 8, Title = "ROOM 8" };
            Room R9 = new Room() { Id = 9, Title = "ROOM 9" };
            Room R10 = new Room() { Id = 10, Title = "ROOM 10" };
            Room R11 = new Room() { Id = 11, Title = "ROOM 11" };
            Room R12 = new Room() { Id = 12, Title = "ROOM 12" };
            Room R13 = new Room() { Id = 13, Title = "ROOM 13" };
            Room R14 = new Room() { Id = 14, Title = "ROOM 14" };
            Room R15 = new Room() { Id = 15, Title = "ROOM 15" };
            Room R16 = new Room() { Id = 16, Title = "ROOM 16" };
            Room R17 = new Room() { Id = 17, Title = "ROOM 17" };
            Room R18 = new Room() { Id = 18, Title = "ROOM 18" };
            Room R19 = new Room() { Id = 19, Title = "ROOM 19" };
            Room R20 = new Room() { Id = 20, Title = "ROOM 20" };
            Room R21 = new Room() { Id = 21, Title = "ROOM 21" };
            Room R22 = new Room() { Id = 22, Title = "ROOM 22" };
            Room R23 = new Room() { Id = 23, Title = "ROOM 23" };
            Room R24 = new Room() { Id = 24, Title = "ROOM 24" };
            Room R25 = new Room() { Id = 25, Title = "ROOM 25" };
            Room R26 = new Room() { Id = 26, Title = "ROOM 26" };
            Room R27 = new Room() { Id = 27, Title = "ROOM 27" };
            Room R28 = new Room() { Id = 28, Title = "ROOM 28" };
            Room R29 = new Room() { Id = 29, Title = "ROOM 29" };
            Room R30 = new Room() { Id = 30, Title = "ROOM 30" };

            Patient P1 = new Patient() { Id = 1, FirstName = "Shirley ", LastName = "Hudson", Age = 43, EntryDate = new DateTime(2020, 1, 1), ExitDate = new DateTime(2020, 1, 11), address = A16, doctor = DO1, room = R1, disease = D1 };
            Patient P2 = new Patient() { Id = 2, FirstName = "Jaslyn ", LastName = "Sanders", Age = 32, EntryDate = new DateTime(2020, 2, 2), ExitDate = new DateTime(2020, 2, 12), address = A17, doctor = DO2, room = R2, disease = D2 };
            Patient P3 = new Patient() { Id = 3, FirstName = "Travis ", LastName = "Moran", Age = 42, EntryDate = new DateTime(2020, 3, 3), ExitDate = new DateTime(2020, 3, 13), address = A18, doctor = DO3, room = R3, disease = D3 };
            Patient P4 = new Patient() { Id = 4, FirstName = "Adrien ", LastName = "Singh", Age = 12, EntryDate = new DateTime(2020, 4, 4), ExitDate = new DateTime(2020, 4, 14), address = A19, doctor = DO4, room = R4, disease = D4 };
            Patient P5 = new Patient() { Id = 5, FirstName = "Skylar ", LastName = "Weaver", Age = 64, EntryDate = new DateTime(2020, 5, 5), ExitDate = new DateTime(2020, 5, 15), address = A20, doctor = DO5, room = R5, disease = D5 };
            Patient P6 = new Patient() { Id = 6, FirstName = "Ruby ", LastName = "Mccann", Age = 63, EntryDate = new DateTime(2020, 6, 6), ExitDate = new DateTime(2020, 6, 16), address = A21, doctor = DO6, room = R6, disease = D6 };
            Patient P7 = new Patient() { Id = 7, FirstName = "Alexis ", LastName = "Trevino", Age = 32, EntryDate = new DateTime(2020, 7, 7), ExitDate = new DateTime(2020, 7, 17), address = A22, doctor = DO7, room = R7, disease = D7 };
            Patient P8 = new Patient() { Id = 8, FirstName = "Paisley ", LastName = "Hobbs", Age = 75, EntryDate = new DateTime(2020, 8, 8), ExitDate = new DateTime(2020, 8, 18), address = A23, doctor = DO8, room = R8, disease = D8 };
            Patient P9 = new Patient() { Id = 9, FirstName = "Naima ", LastName = "Brewer", Age = 69, EntryDate = new DateTime(2020, 9, 9), ExitDate = new DateTime(2020, 9, 19), address = A24, doctor = DO9, room = R9, disease = D9 };
            Patient P10 = new Patient() { Id = 10, FirstName = "Madalynn ", LastName = "Walters", Age = 42, EntryDate = new DateTime(2020, 10, 10), ExitDate = new DateTime(2020, 10, 20), address = A25, doctor = DO10, room = R10, disease = D10 };
            Patient P11 = new Patient() { Id = 11, FirstName = "Kate ", LastName = "Smith", Age = 84, EntryDate = new DateTime(2020, 11, 11), ExitDate = new DateTime(2020, 11, 21), address = A26, doctor = DO11, room = R11, disease = D11 };
            Patient P12 = new Patient() { Id = 12, FirstName = "Carsen ", LastName = "Boyle", Age = 52, EntryDate = new DateTime(2020, 12, 12), ExitDate = new DateTime(2020, 12, 22), address = A27, doctor = DO12, room = R12, disease = D12 };
            Patient P13 = new Patient() { Id = 13, FirstName = "Alanna ", LastName = "Huynh", Age = 65, EntryDate = new DateTime(2020, 3, 13), ExitDate = new DateTime(2020, 3, 23), address = A28, doctor = DO13, room = R13, disease = D13 };
            Patient P14 = new Patient() { Id = 14, FirstName = "Kyan ", LastName = "Wyatt", Age = 64, EntryDate = new DateTime(2020, 4, 14), ExitDate = new DateTime(2020, 4, 24), address = A29, doctor = DO14, room = R14, disease = D14 };
            Patient P15 = new Patient() { Id = 15, FirstName = "Ava ", LastName = "Alvarez", Age = 95, EntryDate = new DateTime(2020, 5, 15), ExitDate = new DateTime(2020, 5, 25), address = A30, doctor = DO15, room = R15, disease = D15 };
            Patient P16 = new Patient() { Id = 16, FirstName = "Maxim ", LastName = "Aguilar", Age = 14, EntryDate = new DateTime(2020, 6, 16), ExitDate = new DateTime(2020, 6, 26), address = A16, doctor = DO1, room = R1, disease = D1 };
            Patient P17 = new Patient() { Id = 17, FirstName = "Monica ", LastName = "Scott", Age = 53, EntryDate = new DateTime(2020, 7, 17), ExitDate = new DateTime(2020, 7, 27), address = A17, doctor = DO2, room = R2, disease = D2 };
            Patient P18 = new Patient() { Id = 18, FirstName = "Melany ", LastName = "Coleman", Age = 53, EntryDate = new DateTime(2020, 8, 18), ExitDate = new DateTime(2020, 8, 28), address = A18, doctor = DO3, room = R3, disease = D3 };
            Patient P19 = new Patient() { Id = 19, FirstName = "Antoine ", LastName = "White", Age = 96, EntryDate = new DateTime(2020, 9, 19), ExitDate = new DateTime(2020, 9, 29), address = A19, doctor = DO4, room = R4, disease = D4 };
            Patient P20 = new Patient() { Id = 20, FirstName = "Branson ", LastName = "Costa", Age = 101, EntryDate = new DateTime(2020, 10, 20), ExitDate = new DateTime(2020, 10, 30), address = A20, doctor = DO5, room = R5, disease = D5 };
            Patient P21 = new Patient() { Id = 21, FirstName = "Emmy ", LastName = "Levine", Age = 69, EntryDate = new DateTime(2020, 11, 21), ExitDate = new DateTime(2020, 12, 1), address = A21, doctor = DO6, room = R6, disease = D6 };
            Patient P22 = new Patient() { Id = 22, FirstName = "Jaelynn ", LastName = "Ochoa", Age = 74, EntryDate = new DateTime(2020, 12, 22), ExitDate = new DateTime(2021, 1, 2), address = A22, doctor = DO7, room = R7, disease = D7 };
            Patient P23 = new Patient() { Id = 23, FirstName = "Sydnee ", LastName = "Collier", Age = 26, EntryDate = new DateTime(2020, 4, 23), ExitDate = new DateTime(2020, 5, 3), address = A23, doctor = DO8, room = R8, disease = D8 };
            Patient P24 = new Patient() { Id = 24, FirstName = "Dario ", LastName = "Lin", Age = 42, EntryDate = new DateTime(2020, 5, 24), ExitDate = new DateTime(2020, 6, 4), address = A24, doctor = DO9, room = R9, disease = D9 };
            Patient P25 = new Patient() { Id = 25, FirstName = "Parker", LastName = "Gillespie", Age = 31, EntryDate = new DateTime(2020, 6, 25), ExitDate = new DateTime(2020, 7, 5), address = A25, doctor = DO10, room = R10, disease = D10 };
            Patient P26 = new Patient() { Id = 26, FirstName = "Mathias ", LastName = "Steele", Age = 36, EntryDate = new DateTime(2020, 7, 26), ExitDate = new DateTime(2020, 8, 6), address = A26, doctor = DO11, room = R11, disease = D11 };
            Patient P27 = new Patient() { Id = 27, FirstName = "Parker ", LastName = "Gillespie", Age = 74, EntryDate = new DateTime(2020, 8, 27), ExitDate = new DateTime(2020, 9, 7), address = A27, doctor = DO12, room = R12, disease = D12 };
            Patient P28 = new Patient() { Id = 28, FirstName = "Mathias ", LastName = "Steele", Age = 34, EntryDate = new DateTime(2020, 9, 28), ExitDate = new DateTime(2020, 10, 9), address = A28, doctor = DO13, room = R13, disease = D13 };
            Patient P29 = new Patient() { Id = 29, FirstName = "London", LastName = "Wu", Age = 88, EntryDate = new DateTime(2020, 10, 29), ExitDate = new DateTime(2020, 11, 10), address = A29, doctor = DO14, room = R14, disease = D14 };
            Patient P30 = new Patient() { Id = 30, FirstName = "Bradyn ", LastName = "Weiss", Age = 33, EntryDate = new DateTime(2020, 11, 30), ExitDate = new DateTime(2020, 12, 11), address = A30, doctor = DO15, room = R15, disease = D15 };




            DO1.Patients.Add(P1);
            DO1.Patients.Add(P2);
            DO2.Patients.Add(P3);
            DO2.Patients.Add(P4);
            DO3.Patients.Add(P5);
            DO3.Patients.Add(P6);
            DO4.Patients.Add(P7);
            DO4.Patients.Add(P8);
            DO5.Patients.Add(P9);
            DO5.Patients.Add(P10);
            DO6.Patients.Add(P11);
            DO6.Patients.Add(P12);
            DO7.Patients.Add(P13);
            DO7.Patients.Add(P14);
            DO8.Patients.Add(P15);
            DO8.Patients.Add(P16);
            DO9.Patients.Add(P17);
            DO9.Patients.Add(P18);
            DO10.Patients.Add(P19);
            DO10.Patients.Add(P20);
            DO11.Patients.Add(P21);
            DO11.Patients.Add(P22);
            DO12.Patients.Add(P23);
            DO12.Patients.Add(P24);
            DO13.Patients.Add(P25);
            DO13.Patients.Add(P26);
            DO14.Patients.Add(P27);
            DO14.Patients.Add(P28);
            DO15.Patients.Add(P29);
            DO15.Patients.Add(P30);

            doctors.Add(DO1);
            doctors.Add(DO2);
            doctors.Add(DO3);
            doctors.Add(DO4);
            doctors.Add(DO5);
            doctors.Add(DO6);
            doctors.Add(DO7);
            doctors.Add(DO8);
            doctors.Add(DO9);
            doctors.Add(DO10);
            doctors.Add(DO11);
            doctors.Add(DO12);
            doctors.Add(DO13);
            doctors.Add(DO14);
            doctors.Add(DO15);
            doctors.Add(DO16);
            doctors.Add(DO17);
            doctors.Add(DO18);
            doctors.Add(DO19);
            doctors.Add(DO20);
            doctors.Add(DO21);
            doctors.Add(DO22);
            doctors.Add(DO23);
            doctors.Add(DO24);
            doctors.Add(DO25);
            doctors.Add(DO26);
            doctors.Add(DO27);
            doctors.Add(DO28);
            doctors.Add(DO29);
            doctors.Add(DO30);

            A1.doctors.Add(DO1);
            A1.doctors.Add(DO16);
            A2.doctors.Add(DO2);
            A2.doctors.Add(DO17);
            A3.doctors.Add(DO3);
            A3.doctors.Add(DO18);
            A4.doctors.Add(DO4);
            A4.doctors.Add(DO19);
            A5.doctors.Add(DO5);
            A5.doctors.Add(DO20);
            A6.doctors.Add(DO6);
            A6.doctors.Add(DO21);
            A7.doctors.Add(DO7);
            A7.doctors.Add(DO22);
            A8.doctors.Add(DO8);
            A8.doctors.Add(DO23);
            A9.doctors.Add(DO9);
            A9.doctors.Add(DO24);
            A10.doctors.Add(DO10);
            A10.doctors.Add(DO25);
            A11.doctors.Add(DO11);
            A11.doctors.Add(DO26);
            A12.doctors.Add(DO12);
            A12.doctors.Add(DO27);
            A13.doctors.Add(DO13);
            A13.doctors.Add(DO28);
            A14.doctors.Add(DO14);
            A14.doctors.Add(DO29);
            A15.doctors.Add(DO15);
            A15.doctors.Add(DO30);

            A16.Patients.Add(P1);
            A16.Patients.Add(P16);
            A17.Patients.Add(P2);
            A17.Patients.Add(P17);
            A18.Patients.Add(P3);
            A18.Patients.Add(P18);
            A19.Patients.Add(P4);
            A19.Patients.Add(P19);
            A20.Patients.Add(P5);
            A20.Patients.Add(P20);
            A21.Patients.Add(P6);
            A21.Patients.Add(P21);
            A22.Patients.Add(P7);
            A22.Patients.Add(P22);
            A23.Patients.Add(P8);
            A23.Patients.Add(P23);
            A24.Patients.Add(P9);
            A24.Patients.Add(P24);
            A25.Patients.Add(P10);
            A25.Patients.Add(P25);
            A26.Patients.Add(P11);
            A26.Patients.Add(P26);
            A27.Patients.Add(P12);
            A27.Patients.Add(P27);
            A28.Patients.Add(P13);
            A28.Patients.Add(P28);
            A29.Patients.Add(P14);
            A29.Patients.Add(P29);
            A30.Patients.Add(P15);
            A30.Patients.Add(P30);

            addresses.Add(A1);
            addresses.Add(A2);
            addresses.Add(A3);
            addresses.Add(A4);
            addresses.Add(A5);
            addresses.Add(A6);
            addresses.Add(A7);
            addresses.Add(A8);
            addresses.Add(A9);
            addresses.Add(A10);
            addresses.Add(A11);
            addresses.Add(A12);
            addresses.Add(A13);
            addresses.Add(A14);
            addresses.Add(A15);
            addresses.Add(A16);
            addresses.Add(A17);
            addresses.Add(A18);
            addresses.Add(A19);
            addresses.Add(A20);
            addresses.Add(A21);
            addresses.Add(A22);
            addresses.Add(A23);
            addresses.Add(A24);
            addresses.Add(A25);
            addresses.Add(A26);
            addresses.Add(A27);
            addresses.Add(A28);
            addresses.Add(A29);
            addresses.Add(A30);

            patients.Add(P1);
            patients.Add(P2);
            patients.Add(P3);
            patients.Add(P4);
            patients.Add(P5);
            patients.Add(P6);
            patients.Add(P7);
            patients.Add(P8);
            patients.Add(P9);
            patients.Add(P10);
            patients.Add(P11);
            patients.Add(P12);
            patients.Add(P13);
            patients.Add(P14);
            patients.Add(P15);
            patients.Add(P16);
            patients.Add(P17);
            patients.Add(P18);
            patients.Add(P19);
            patients.Add(P20);
            patients.Add(P21);
            patients.Add(P22);
            patients.Add(P23);
            patients.Add(P24);
            patients.Add(P25);
            patients.Add(P26);
            patients.Add(P27);
            patients.Add(P28);
            patients.Add(P29);
            patients.Add(P30);

            R1.Patients.Add(P1);
            R1.Patients.Add(P16);
            R2.Patients.Add(P2);
            R2.Patients.Add(P17);
            R3.Patients.Add(P3);
            R3.Patients.Add(P18);
            R4.Patients.Add(P4);
            R4.Patients.Add(P19);
            R5.Patients.Add(P5);
            R5.Patients.Add(P20);
            R6.Patients.Add(P6);
            R6.Patients.Add(P21);
            R7.Patients.Add(P7);
            R7.Patients.Add(P22);
            R8.Patients.Add(P8);
            R8.Patients.Add(P23);
            R9.Patients.Add(P9);
            R9.Patients.Add(P24);
            R10.Patients.Add(P10);
            R10.Patients.Add(P25);
            R11.Patients.Add(P11);
            R11.Patients.Add(P26);
            R12.Patients.Add(P12);
            R12.Patients.Add(P27);
            R13.Patients.Add(P13);
            R13.Patients.Add(P28);
            R14.Patients.Add(P14);
            R14.Patients.Add(P29);
            R15.Patients.Add(P15);
            R15.Patients.Add(P30);

            rooms.Add(R1);
            rooms.Add(R2);
            rooms.Add(R3);
            rooms.Add(R4);
            rooms.Add(R5);
            rooms.Add(R6);
            rooms.Add(R7);
            rooms.Add(R8);
            rooms.Add(R9);
            rooms.Add(R10);
            rooms.Add(R11);
            rooms.Add(R12);
            rooms.Add(R13);
            rooms.Add(R14);
            rooms.Add(R15);
            rooms.Add(R16);
            rooms.Add(R17);
            rooms.Add(R18);
            rooms.Add(R19);
            rooms.Add(R20);
            rooms.Add(R21);
            rooms.Add(R22);
            rooms.Add(R23);
            rooms.Add(R24);
            rooms.Add(R25);
            rooms.Add(R26);
            rooms.Add(R27);
            rooms.Add(R28);
            rooms.Add(R29);
            rooms.Add(R30);


            D1.patients.Add(P1);
            D1.patients.Add(P16);
            D2.patients.Add(P2);
            D2.patients.Add(P17);
            D3.patients.Add(P3);
            D3.patients.Add(P18);
            D4.patients.Add(P4);
            D4.patients.Add(P19);
            D5.patients.Add(P5);
            D5.patients.Add(P20);
            D6.patients.Add(P6);
            D6.patients.Add(P21);
            D7.patients.Add(P7);
            D7.patients.Add(P22);
            D8.patients.Add(P8);
            D8.patients.Add(P23);
            D9.patients.Add(P9);
            D9.patients.Add(P24);
            D10.patients.Add(P10);
            D10.patients.Add(P25);
            D11.patients.Add(P11);
            D11.patients.Add(P26);
            D12.patients.Add(P12);
            D12.patients.Add(P27);
            D13.patients.Add(P13);
            D13.patients.Add(P28);
            D14.patients.Add(P14);
            D14.patients.Add(P29);
            D15.patients.Add(P15);
            D15.patients.Add(P30);

            diseases.Add(D1);
            diseases.Add(D2);
            diseases.Add(D3);
            diseases.Add(D4);
            diseases.Add(D5);
            diseases.Add(D6);
            diseases.Add(D7);
            diseases.Add(D8);
            diseases.Add(D9);
            diseases.Add(D10);
            diseases.Add(D11);
            diseases.Add(D12);
            diseases.Add(D13);
            diseases.Add(D14);
            diseases.Add(D15);
            diseases.Add(D16);
            diseases.Add(D17);
            diseases.Add(D18);
            diseases.Add(D19);
            diseases.Add(D20);
            diseases.Add(D21);
            diseases.Add(D22);
            diseases.Add(D23);
            diseases.Add(D24);
            diseases.Add(D25);
            diseases.Add(D26);
            diseases.Add(D27);
            diseases.Add(D28);
            diseases.Add(D29);
            diseases.Add(D30);


        }
        private static MyDatabase _instance;
        public static MyDatabase GetInstance()
        {
            if (_instance == null)
            {
                _instance = new MyDatabase();
            }
            return _instance;
        }
    }
}
